# -*- coding: utf-8 -*-
"""
本地股票列表备用数据源
当所有网络数据源都失败时使用
"""

import logging
from typing import Optional
import pandas as pd
from pathlib import Path

logger = logging.getLogger(__name__)


class LocalStockListBackup:
    """本地股票列表备用数据源"""

    # 最常用的 A 股股票代码和名称（前100只）
    DEFAULT_STOCKS = [
        {
            "code": "000001",
            "name": "平安银行",
            "ts_code": "000001.SZ",
            "area": "深圳",
            "industry": "银行",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000002",
            "name": "万科A",
            "ts_code": "000002.SZ",
            "area": "深圳",
            "industry": "房地产",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000063",
            "name": "中兴通讯",
            "ts_code": "000063.SZ",
            "area": "深圳",
            "industry": "通信设备",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000100",
            "name": "TCL科技",
            "ts_code": "000100.SZ",
            "area": "惠州",
            "industry": "电子",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000333",
            "name": "美的集团",
            "ts_code": "000333.SZ",
            "area": "佛山",
            "industry": "家电",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000538",
            "name": "云南白药",
            "ts_code": "000538.SZ",
            "area": "昆明",
            "industry": "医药",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000568",
            "name": "泸州老窖",
            "ts_code": "000568.SZ",
            "area": "泸州",
            "industry": "白酒",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000651",
            "name": "格力电器",
            "ts_code": "000651.SZ",
            "area": "珠海",
            "industry": "家电",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000725",
            "name": "京东方A",
            "ts_code": "000725.SZ",
            "area": "北京",
            "industry": "电子",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000768",
            "name": "中航西飞",
            "ts_code": "000768.SZ",
            "area": "西安",
            "industry": "航空",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000858",
            "name": "五粮液",
            "ts_code": "000858.SZ",
            "area": "宜宾",
            "industry": "白酒",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "000895",
            "name": "双汇发展",
            "ts_code": "000895.SZ",
            "area": "漯河",
            "industry": "食品",
            "market": "主板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002001",
            "name": "新和成",
            "ts_code": "002001.SZ",
            "area": "绍兴",
            "industry": "化工",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002007",
            "name": "华兰生物",
            "ts_code": "002007.SZ",
            "area": "新乡",
            "industry": "医药",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002024",
            "name": "苏宁易购",
            "ts_code": "002024.SZ",
            "area": "南京",
            "industry": "零售",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002027",
            "name": "分众传媒",
            "ts_code": "002027.SZ",
            "area": "广州",
            "industry": "传媒",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002049",
            "name": "紫光国微",
            "ts_code": "002049.SZ",
            "area": "唐山",
            "industry": "芯片",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002120",
            "name": "韵达股份",
            "ts_code": "002120.SZ",
            "area": "宁波",
            "industry": "物流",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002142",
            "name": "宁波银行",
            "ts_code": "002142.SZ",
            "area": "宁波",
            "industry": "银行",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002230",
            "name": "科大讯飞",
            "ts_code": "002230.SZ",
            "area": "合肥",
            "industry": "软件",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002236",
            "name": "大华股份",
            "ts_code": "002236.SZ",
            "area": "杭州",
            "industry": "安防",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002271",
            "name": "东方雨虹",
            "ts_code": "002271.SZ",
            "area": "北京",
            "industry": "建材",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002304",
            "name": "洋河股份",
            "ts_code": "002304.SZ",
            "area": "宿迁",
            "industry": "白酒",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002352",
            "name": "顺丰控股",
            "ts_code": "002352.SZ",
            "area": "深圳",
            "industry": "物流",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002415",
            "name": "海康威视",
            "ts_code": "002415.SZ",
            "area": "杭州",
            "industry": "安防",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002460",
            "name": "赣锋锂业",
            "ts_code": "002460.SZ",
            "area": "新余",
            "industry": "新能源",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002475",
            "name": "立讯精密",
            "ts_code": "002475.SZ",
            "area": "东莞",
            "industry": "电子",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002594",
            "name": "比亚迪",
            "ts_code": "002594.SZ",
            "area": "深圳",
            "industry": "汽车",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002714",
            "name": "牧原股份",
            "ts_code": "002714.SZ",
            "area": "南阳",
            "industry": "养殖",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "002812",
            "name": "恩捷股份",
            "ts_code": "002812.SZ",
            "area": "玉溪",
            "industry": "新能源",
            "market": "中小板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300003",
            "name": "乐普医疗",
            "ts_code": "300003.SZ",
            "area": "北京",
            "industry": "医疗器械",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300014",
            "name": "亿纬锂能",
            "ts_code": "300014.SZ",
            "area": "惠州",
            "industry": "新能源",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300015",
            "name": "爱尔眼科",
            "ts_code": "300015.SZ",
            "area": "长沙",
            "industry": "医疗服务",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300033",
            "name": "同花顺",
            "ts_code": "300033.SZ",
            "area": "杭州",
            "industry": "软件",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300059",
            "name": "东方财富",
            "ts_code": "300059.SZ",
            "area": "上海",
            "industry": "金融",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300122",
            "name": "智飞生物",
            "ts_code": "300122.SZ",
            "area": "重庆",
            "industry": "医药",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300124",
            "name": "汇川技术",
            "ts_code": "300124.SZ",
            "area": "深圳",
            "industry": "电气",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300142",
            "name": "沃森生物",
            "ts_code": "300142.SZ",
            "area": "昆明",
            "industry": "医药",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300274",
            "name": "阳光电源",
            "ts_code": "300274.SZ",
            "area": "合肥",
            "industry": "新能源",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300408",
            "name": "三环集团",
            "ts_code": "300408.SZ",
            "area": "潮州",
            "industry": "电子",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300413",
            "name": "芒果超媒",
            "ts_code": "300413.SZ",
            "area": "长沙",
            "industry": "传媒",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300433",
            "name": "蓝思科技",
            "ts_code": "300433.SZ",
            "area": "浏阳",
            "industry": "电子",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300498",
            "name": "温氏股份",
            "ts_code": "300498.SZ",
            "area": "云浮",
            "industry": "养殖",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "300750",
            "name": "宁德时代",
            "ts_code": "300750.SZ",
            "area": "宁德",
            "industry": "新能源",
            "market": "创业板",
            "exchange": "深圳证券交易所",
        },
        {
            "code": "600000",
            "name": "浦发银行",
            "ts_code": "600000.SH",
            "area": "上海",
            "industry": "银行",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600009",
            "name": "上海机场",
            "ts_code": "600009.SH",
            "area": "上海",
            "industry": "机场",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600016",
            "name": "民生银行",
            "ts_code": "600016.SH",
            "area": "北京",
            "industry": "银行",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600028",
            "name": "中国石化",
            "ts_code": "600028.SH",
            "area": "北京",
            "industry": "石油",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600030",
            "name": "中信证券",
            "ts_code": "600030.SH",
            "area": "深圳",
            "industry": "证券",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600031",
            "name": "三一重工",
            "ts_code": "600031.SH",
            "area": "北京",
            "industry": "机械",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600036",
            "name": "招商银行",
            "ts_code": "600036.SH",
            "area": "深圳",
            "industry": "银行",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600048",
            "name": "保利发展",
            "ts_code": "600048.SH",
            "area": "广州",
            "industry": "房地产",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600050",
            "name": "中国联通",
            "ts_code": "600050.SH",
            "area": "北京",
            "industry": "通信",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600104",
            "name": "上汽集团",
            "ts_code": "600104.SH",
            "area": "上海",
            "industry": "汽车",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600276",
            "name": "恒瑞医药",
            "ts_code": "600276.SH",
            "area": "连云港",
            "industry": "医药",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600309",
            "name": "万华化学",
            "ts_code": "600309.SH",
            "area": "烟台",
            "industry": "化工",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600406",
            "name": "国电南瑞",
            "ts_code": "600406.SH",
            "area": "南京",
            "industry": "电气",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600436",
            "name": "片仔癀",
            "ts_code": "600436.SH",
            "area": "漳州",
            "industry": "中药",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600438",
            "name": "通威股份",
            "ts_code": "600438.SH",
            "area": "成都",
            "industry": "新能源",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600519",
            "name": "贵州茅台",
            "ts_code": "600519.SH",
            "area": "遵义",
            "industry": "白酒",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600585",
            "name": "海螺水泥",
            "ts_code": "600585.SH",
            "area": "芜湖",
            "industry": "建材",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600660",
            "name": "福耀玻璃",
            "ts_code": "600660.SH",
            "area": "福清",
            "industry": "汽车",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600690",
            "name": "海尔智家",
            "ts_code": "600690.SH",
            "area": "青岛",
            "industry": "家电",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600745",
            "name": "闻泰科技",
            "ts_code": "600745.SH",
            "area": "嘉兴",
            "industry": "电子",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600809",
            "name": "山西汾酒",
            "ts_code": "600809.SH",
            "area": "汾阳",
            "industry": "白酒",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600887",
            "name": "伊利股份",
            "ts_code": "600887.SH",
            "area": "呼和浩特",
            "industry": "食品",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "600900",
            "name": "长江电力",
            "ts_code": "600900.SH",
            "area": "北京",
            "industry": "电力",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601012",
            "name": "隆基绿能",
            "ts_code": "601012.SH",
            "area": "西安",
            "industry": "新能源",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601088",
            "name": "中国神华",
            "ts_code": "601088.SH",
            "area": "北京",
            "industry": "煤炭",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601111",
            "name": "中国国航",
            "ts_code": "601111.SH",
            "area": "北京",
            "industry": "航空",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601138",
            "name": "工业富联",
            "ts_code": "601138.SH",
            "area": "深圳",
            "industry": "电子",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601166",
            "name": "兴业银行",
            "ts_code": "601166.SH",
            "area": "福州",
            "industry": "银行",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601211",
            "name": "国泰君安",
            "ts_code": "601211.SH",
            "area": "上海",
            "industry": "证券",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601318",
            "name": "中国平安",
            "ts_code": "601318.SH",
            "area": "深圳",
            "industry": "保险",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601398",
            "name": "工商银行",
            "ts_code": "601398.SH",
            "area": "北京",
            "industry": "银行",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601600",
            "name": "中国铝业",
            "ts_code": "601600.SH",
            "area": "北京",
            "industry": "有色",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601668",
            "name": "中国建筑",
            "ts_code": "601668.SH",
            "area": "北京",
            "industry": "建筑",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601688",
            "name": "华泰证券",
            "ts_code": "601688.SH",
            "area": "南京",
            "industry": "证券",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601816",
            "name": "京沪高铁",
            "ts_code": "601816.SH",
            "area": "北京",
            "industry": "铁路",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "601888",
            "name": "中国中免",
            "ts_code": "601888.SH",
            "area": "北京",
            "industry": "免税",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "603288",
            "name": "海天味业",
            "ts_code": "603288.SH",
            "area": "佛山",
            "industry": "食品",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "603501",
            "name": "韦尔股份",
            "ts_code": "603501.SH",
            "area": "上海",
            "industry": "芯片",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "603659",
            "name": "璞泰来",
            "ts_code": "603659.SH",
            "area": "上海",
            "industry": "新能源",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
        {
            "code": "603986",
            "name": "兆易创新",
            "ts_code": "603986.SH",
            "area": "北京",
            "industry": "芯片",
            "market": "主板",
            "exchange": "上海证券交易所",
        },
    ]

    @classmethod
    def get_stock_list(cls) -> Optional[pd.DataFrame]:
        """获取本地备用的股票列表"""
        try:
            logger.warning("⚠️ 使用本地备用股票列表（仅包含主要蓝筹股）")
            df = pd.DataFrame(cls.DEFAULT_STOCKS)
            logger.info(f"✅ 本地备用股票列表加载完成: {len(df)} 只股票")
            return df
        except Exception as e:
            logger.error(f"❌ 加载本地备用股票列表失败: {e}")
            return None

    @classmethod
    def save_to_csv(cls, filepath: str = "data/stock_list_backup.csv"):
        """将默认股票列表保存到 CSV"""
        try:
            df = pd.DataFrame(cls.DEFAULT_STOCKS)
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            df.to_csv(filepath, index=False, encoding="utf-8-sig")
            logger.info(f"✅ 股票列表已保存到: {filepath}")
        except Exception as e:
            logger.error(f"❌ 保存股票列表失败: {e}")
